---
name: 'Release'

on:
  push:
    branches:
      - main

jobs:
  release:
    name: 'Release'
    runs-on: 'ubuntu-latest'
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0

      - name: Setup ionic and capacitor
        run: |
          npm i -g @ionic/cli @capacitor/cli yarn

      - name: Install node modules
        run: yarn

      - name: Build app for android
        run: |
          CI=false
          yarn build
          npx cap sync android
          ionic capacitor update
          ionic capacitor copy android
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
          ./gradlew assembleRelease
          cd ..
          CI=true

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        run: |
          CI=false
          yarn semantic-release
