name: 'Release'
on:
  push:
    branches:
      - main
      - beta
jobs:
  release:
    name: 'Release'
    runs-on: 'ubuntu-latest'
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
      - name: Setup ionic and capacitor
        run: |
          npm i -g @ionic/cli @capacitor/cli yarn
      - name: Install node modules
        run: yarn
      - name: Build and Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TELEGRAM_BOT_ID: ${{ secrets.TELEGRAM_BOT_ID }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: |
          yarn semantic-release
