name: 'Telegram - Debug Apk'
on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  telegram-debug-apk:
    name: 'Telegram - Debug Apk'
    runs-on: 'ubuntu-latest'
    permissions: write-all
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
      - name: Setup ionic and capacitor
        run: |
          npm i -g @ionic/cli @capacitor/cli yarn
      - name: Install node modules
        run: yarn
      - name: Build android
        run: |
          yarn build
          npx cap sync android
          ionic capacitor update
          ionic capacitor copy android
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
          ./gradlew assembleRelease
          cd ..
      - name: Send telegram message with dubug apk
        uses: appleboy/telegram-action@master
        with:
          to: -877507563
          token: ${{ secrets.TELEGRAM_BOT_API_KEY }}
          document: android/app/build/outputs/apk/debug/app-debug.apk
